version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_db
    ports:
      - "3306:3306"
    volumes:
    - ./src/Infra/Database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  integrador-app:
    build: .
    container_name: integrador-app
    ports:
      - "8080:8080"
    command: tail -f /dev/null # Keep the container running
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

    env_file:
      - .env
